version: '3.8'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./organizations_db/data:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    depends_on:
      - mongo
    ports:
      - "5000:5000"
